apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment.apps/simple-http-server-deploymen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: ghcr.io/cprimetraining101/simple-http-server
        ports:
        - containerPort: 8080